name = "valyr-worker-dev"
main = "src/index.ts"
compatibility_date = "2022-11-29"
node_compat = true


[vars]
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSJ9.vI9obAHOGyVVKa3pD--kJlyxp-Z2zV9UUMAhKpNLAcU"
SUPABASE_URL = "http://localhost:54321"

[env.production]
name = "valyr-worker-prod"

[env.production.vars]
SUPABASE_SERVICE_ROLE_KEY = "todo"
SUPABASE_URL = "todo"

